export enum Routes {
  LOGIN = 'LOGIN',
  TAB_NAVIGATOR = 'MAIN_TAB_NAVIGATOR',
  CONFIGURE_TASK = 'CONFIGURE_TASK',
  COMPLETED_TASKS_LIST = 'COMPLETED_TASKS_LIST',
  ITEM_LIST = 'ITEM_LIST',
}

export enum TabRouts {
  TASK_LIST = 'TASK_LIST',
  MAP = 'MAP',
  ANIMATION = 'ANIMATION',
  GENERATOR = 'GENERATOR',
}
